
services:

  demo-service:
    image: "ghcr.io/tpmacc/demo-service"
    container_name: "demo-service"
    ports:
      - 8002:8002
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
